<?php

namespace app\core;


class HttpBearerAuth extends \yii\filters\auth\HttpBearerAuth
{
    /**
     * @inheritdoc
     */
    public function authenticate($user, $request, $response)
    {
        $authHeader = $request->getHeaders()->get('WWW-Authorization');
        if ($authHeader !== null && preg_match('/^Bearer\s+(.*?)$/', $authHeader, $matches)) {
            $identity = $user->loginByAccessToken($matches[1], get_class($this));
            if ($identity === null) {
                $this->handleFailure($response);
            }
            return $identity;
        }

        return null;
    }

    function beforeAction($action)
    {
        if (\Yii::$app->request->isOptions)
            return true;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}